# Generated by Django 4.2.30 on 2026-04-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interested_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
