from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<str:category_name>/', views.category, name='category'),
    path('discussion/<str:post_id>/', views.discussion, name='discussion'),
    path('profile/', views.profile, name='profile'),
    path('search/', views.search, name='search'),
    path('search/quick/', views.quick_search, name='quick_search'),
    path('ask/', views.ask_question, name='ask_question'),
    path('notifications/', views.notifications, name='notifications'),
    path('notifications/count/', views.notification_count, name='notification_count'),
    path('chats/list/', views.chat_list, name='chat_list'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('create-post/', views.create_post, name='create_post'),
    path('posts/<str:post_id>/update/', views.update_post, name='update_post'),
    path('posts/<str:post_id>/delete/', views.delete_post, name='delete_post'),
    path('discussion/<str:post_id>/comment/', views.create_comment, name='create_comment'),
    path('like-comment/', views.like_comment, name='like_comment'),
    path('start-debate/', views.start_debate, name='start_debate'),
    path('report-comment/', views.report_comment, name='report_comment'),
    path('update-comment/', views.update_comment, name='update_comment'),
    path('accept-debate/<str:debate_id>/', views.accept_debate, name='accept_debate'),
    path('reject-debate/<str:debate_id>/', views.reject_debate, name='reject_debate'),
    path('debates/<str:debate_id>/chat/', views.debate_chat, name='debate_chat'),
    path('debates/<str:debate_id>/messages/', views.send_debate_message, name='send_debate_message'),
    path('debates/<str:debate_id>/messages/list/', views.debate_messages, name='debate_messages'),
    path('debates/<str:debate_id>/info/', views.debate_info, name='debate_info'),
    path('debates/<str:debate_id>/leave/', views.leave_debate, name='leave_debate'),
    path('debates/<str:debate_id>/rejoin/', views.rejoin_debate, name='rejoin_debate'),
    path('debates/<str:debate_id>/increase-limits/', views.increase_debate_limits, name='increase_debate_limits'),
    path('debates/<str:debate_id>/end/', views.end_debate, name='end_debate'),
    path('debates/<str:debate_id>/remove-participant/', views.remove_debate_participant, name='remove_debate_participant'),
]