from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('suggested/', views.suggested, name='suggested'),
    path('category/<str:category_name>/', views.category, name='category'),
    path('discussion/<str:post_id>/', views.discussion, name='discussion'),
    path('profile/', views.profile, name='profile'),
    path('profile/upload-picture/', views.upload_profile_picture, name='upload_profile_picture'),
    path('user/<str:username>/', views.user_profile, name='user_profile'),
    path('user/<str:username>/report/', views.report_user_profile, name='report_user_profile'),
    path('search/', views.search, name='search'),
    path('search/quick/', views.quick_search, name='quick_search'),
    path('search/users/', views.search_users, name='search_users'),
    path('search/hashtags/suggest/', views.hashtag_suggestions, name='hashtag_suggestions'),
    path('search/hashtags/', views.hashtag_search, name='hashtag_search'),
    path('ask/', views.ask_question, name='ask_question'),
    path('notifications/', views.notifications, name='notifications'),
    path('notifications/count/', views.notification_count, name='notification_count'),
    path('notifications/unfollow-post/', views.unfollow_post, name='unfollow_post'),
    path('notifications/dismiss/', views.dismiss_notification, name='dismiss_notification'),
    path('chats/', views.chats, name='chats'),
    path('chats/list/', views.chat_list, name='chat_list'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('check-username/', views.check_username, name='check_username'),
    path('logout/', views.logout_view, name='logout'),
    path('interests/', views.interests_onboarding, name='interests_onboarding'),
    path('interests/save/', views.save_interests, name='save_interests'),
    path('presence/offline/', views.mark_offline, name='mark_offline'),
    path('create-post/', views.create_post, name='create_post'),
    path('profile/remove-follower/', views.remove_follower, name='remove_follower'),
    path('posts/<str:post_id>/action/', views.post_action, name='post_action'),
    path('posts/<str:post_id>/likes/', views.post_likes, name='post_likes'),
    path('posts/<str:post_id>/update/', views.update_post, name='update_post'),
    path('posts/<str:post_id>/delete/', views.delete_post, name='delete_post'),
    path('posts/<str:post_id>/remove-repost/', views.remove_repost, name='remove_repost'),
    path('discussion/<str:post_id>/comment/', views.create_comment, name='create_comment'),
    path('like-comment/', views.like_comment, name='like_comment'),
    path('start-debate/', views.start_debate, name='start_debate'),
    path('report-comment/', views.report_comment, name='report_comment'),
    path('update-comment/', views.update_comment, name='update_comment'),
    path('accept-debate/<str:debate_id>/', views.accept_debate, name='accept_debate'),
    path('reject-debate/<str:debate_id>/', views.reject_debate, name='reject_debate'),
    path('debates/<str:debate_id>/chat/', views.debate_chat, name='debate_chat'),
    path('debates/<str:debate_id>/messages/', views.send_debate_message, name='send_debate_message'),
    path('debates/<str:debate_id>/messages/<int:message_id>/update/', views.update_debate_message, name='update_debate_message'),
    path('debates/<str:debate_id>/messages/<int:message_id>/react/', views.react_to_debate_message, name='react_to_debate_message'),
    path('debates/<str:debate_id>/messages/<int:message_id>/report/', views.report_debate_message, name='report_debate_message'),
    path('debates/<str:debate_id>/messages/list/', views.debate_messages, name='debate_messages'),
    path('moderation/debate-message-reports/<int:report_id>/review/', views.moderate_debate_message_report, name='moderate_debate_message_report'),
    path('moderation/profile-reports/<int:report_id>/review/', views.moderate_profile_report, name='moderate_profile_report'),
    path('debates/<str:debate_id>/info/', views.debate_info, name='debate_info'),
    path('debates/<str:debate_id>/leave/', views.leave_debate, name='leave_debate'),
    path('debates/<str:debate_id>/rejoin/', views.rejoin_debate, name='rejoin_debate'),
    path('debates/<str:debate_id>/increase-limits/', views.increase_debate_limits, name='increase_debate_limits'),
    path('debates/<str:debate_id>/end/', views.end_debate, name='end_debate'),
    path('debates/<str:debate_id>/remove-participant/', views.remove_debate_participant, name='remove_debate_participant'),
    # Polls
    path('polls/<str:poll_id>/action/', views.poll_action, name='poll_action'),
    path('polls/', views.polls_list, name='polls_list'),
    path('polls/create/', views.create_poll, name='create_poll'),
    path('polls/comment/react/', views.like_poll_comment, name='like_poll_comment'),
    path('polls/<str:poll_id>/', views.poll_detail, name='poll_detail'),
    path('polls/<str:poll_id>/vote/', views.poll_vote, name='poll_vote'),
    path('polls/<str:poll_id>/comment/', views.create_poll_comment, name='create_poll_comment'),
    # Questions
    path('questions/<str:question_id>/action/', views.question_action, name='question_action'),
    path('questions/', views.questions_list, name='questions_list'),
    path('questions/ask/', views.ask_general_question, name='ask_general_question'),
    path('questions/answer/<str:answer_id>/vote/', views.vote_answer, name='vote_answer'),
    path('questions/answer/<str:answer_id>/best/', views.mark_best_answer, name='mark_best_answer'),
    path('questions/<str:question_id>/', views.question_detail, name='question_detail'),
    path('questions/<str:question_id>/answer/', views.post_answer, name='post_answer'),
    # Leaderboard
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    # Reviews
    path('reviews/<str:review_id>/action/', views.review_action, name='review_action'),
    path('reviews/', views.reviews_list, name='reviews_list'),
    path('reviews/create/', views.create_review, name='create_review'),
    path('reviews/comment/react/', views.like_review_comment, name='like_review_comment'),
    path('reviews/<str:review_id>/', views.review_detail, name='review_detail'),
    path('reviews/<str:review_id>/react/', views.react_to_review, name='react_to_review'),
    path('reviews/<str:review_id>/comment/', views.create_review_comment, name='create_review_comment'),
    # Trending hashtags
    path('trending/', views.trending_hashtags, name='trending_hashtags'),
    # Activity feed
    path('activity/', views.activity_feed, name='activity_feed'),
    # Debate transcript (public)
    path('debates/<str:debate_id>/transcript/', views.debate_transcript, name='debate_transcript'),
    # Observer voting
    path('debates/<str:debate_id>/observer-vote/', views.observer_vote, name='observer_vote'),
    # User blocking
    path('block-user/', views.block_user, name='block_user'),
    path('unblock-user/', views.unblock_user, name='unblock_user'),
    # Profile bio/website update
    path('profile/update-bio/', views.update_profile_bio, name='update_profile_bio'),
    # Comment reporting
    path('report-post-comment/', views.report_post_comment, name='report_post_comment'),
    # Debate stats JSON
    path('stats/debates/', views.debate_stats, name='debate_stats'),
    path('stats/debates/<str:username>/', views.debate_stats, name='debate_stats_user'),
    # Hashtag following
    path('hashtags/follow/', views.follow_hashtag, name='follow_hashtag'),
    path('hashtags/feed/', views.hashtag_followed_feed, name='hashtag_followed_feed'),
    # Moderation dashboard
    path('moderation/', views.moderation_dashboard, name='moderation_dashboard'),
]