# Generated by Django 4.2.11 on 2026-04-13 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='no_supporters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='debate',
            name='yes_supporters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Sports', 'Sports'), ('Science', 'Science'), ('Politics', 'Politics'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Business', 'Business'), ('Gadgets', 'Gadgets'), ('Vehicles', 'Vehicles'), ('Education', 'Education'), ('Travel', 'Travel'), ('Food', 'Food')], max_length=50),
        ),
        migrations.CreateModel(
            name='DebateMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='discussions.debate')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
