# Generated by Django 4.2.11 on 2026-04-13 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussions', '0003_debatemessage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='end_controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_debates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debate',
            name='end_controller_side',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='DebateParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='discussions.debate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='debateparticipant',
            constraint=models.UniqueConstraint(fields=('debate', 'user'), name='unique_debate_participant'),
        ),
    ]
