# Generated by Django 4.2.11 on 2026-04-13 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussions', '0004_debate_end_controller_debate_end_controller_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debateparticipant',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CommentModeratorBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_comment_owners', to=settings.AUTH_USER_MODEL)),
                ('comment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderated_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='commentmoderatorblock',
            constraint=models.UniqueConstraint(fields=('comment_owner', 'blocked_user'), name='unique_comment_owner_block'),
        ),
    ]
