# Generated by Django 4.2.11 on 2026-04-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0007_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatemessage',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
