# Generated by Django 4.2.11 on 2026-04-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0008_debatemessage_is_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Sports', 'Sports'), ('Science', 'Science'), ('History', 'History'), ('Politics', 'Politics'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Business', 'Business'), ('Gadgets', 'Gadgets'), ('Vehicles', 'Vehicles'), ('Education', 'Education'), ('Travel', 'Travel'), ('Food', 'Food'), ('Investment', 'Investment'), ('Astrology', 'Astrology'), ('Spirituality', 'Spirituality'), ('Others', 'Others')], max_length=50),
        ),
    ]