# Generated by Django 4.2.11 on 2026-04-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0012_edit_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.TextField(blank=True, default='', help_text='Comma-separated hashtags'),
        ),
    ]
