# Generated by Django 4.2.30 on 2026-04-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0014_debatemessagereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post_comment', 'New Comment on Followed Post'), ('post_activity', 'Active Conversation on Followed Post'), ('moderation_alert', 'Moderator Alert'), ('moderation_warning', 'Moderation Warning')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Relationships', 'Relationships'), ('Photography', 'Photography'), ('Music', 'Music'), ('Painting', 'Painting'), ('Fashion', 'Fashion'), ('Beauty', 'Beauty'), ('Medicenes', 'Medicenes'), ('Sports', 'Sports'), ('Science', 'Science'), ('History', 'History'), ('Politics', 'Politics'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Business', 'Business'), ('Gadgets', 'Gadgets'), ('Vehicles', 'Vehicles'), ('Education', 'Education'), ('Travel', 'Travel'), ('Food', 'Food'), ('Investment', 'Investment'), ('Astrology', 'Astrology'), ('Spirituality', 'Spirituality'), ('Others', 'Others')], max_length=50),
        ),
    ]
