# Generated by Django 4.2.30 on 2026-04-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0015_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Astrology', 'Astrology'), ('Beauty', 'Beauty'), ('Business', 'Business'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Gadgets', 'Gadgets'), ('Health', 'Health'), ('History', 'History'), ('Investment', 'Investment'), ('Medicenes', 'Medicenes'), ('Music', 'Music'), ('Painting', 'Painting'), ('Photography', 'Photography'), ('Politics', 'Politics'), ('Relationships', 'Relationships'), ('Science', 'Science'), ('Spirituality', 'Spirituality'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Travel', 'Travel'), ('Vehicles', 'Vehicles'), ('Others', 'Others')], max_length=50),
        ),
    ]
