# Generated by Django 4.2.30 on 2026-04-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0016_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted_by_moderation',
            field=models.BooleanField(default=False, help_text='Automatically deleted by moderation'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flagged by moderation system'),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderation_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for moderation action'),
        ),
        migrations.AddField(
            model_name='debatemessage',
            name='is_deleted_by_moderation',
            field=models.BooleanField(default=False, help_text='Automatically deleted by moderation'),
        ),
        migrations.AddField(
            model_name='debatemessage',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flagged by moderation system'),
        ),
        migrations.AddField(
            model_name='debatemessage',
            name='moderation_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for moderation action'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted_by_moderation',
            field=models.BooleanField(default=False, help_text='Automatically deleted by moderation'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flagged by moderation system'),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for moderation action'),
        ),
    ]
