# Generated by Django 5.2.13 on 2026-05-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0036_mood_draw_readlater"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedscore",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("post_comment", "New Comment on Followed Post"),
                    ("post_activity", "Active Conversation on Followed Post"),
                    ("moderation_alert", "Moderator Alert"),
                    ("moderation_warning", "Moderation Warning"),
                    ("author_comment", "New Comment on Your Post"),
                    ("author_debate", "New Debate on Your Post"),
                    ("author_repost", "Your Post was Reposted"),
                    ("author_save", "Your Post was Saved"),
                    ("mention", "You Were Mentioned"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pollaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pollfollow",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("Astrology", "Astrology"),
                    ("Beauty", "Beauty"),
                    ("Business", "Business"),
                    ("Education", "Education"),
                    ("Entertainment", "Entertainment"),
                    ("Fashion", "Fashion"),
                    ("Food", "Food"),
                    ("Gadgets", "Gadgets"),
                    ("Health", "Health"),
                    ("History", "History"),
                    ("Investment", "Investment"),
                    ("Medicenes", "Medicenes"),
                    ("Music", "Music"),
                    ("Painting", "Painting"),
                    ("Photography", "Photography"),
                    ("Politics", "Politics"),
                    ("Relationships", "Relationships"),
                    ("Science", "Science"),
                    ("Spirituality", "Spirituality"),
                    ("Sports", "Sports"),
                    ("Technology", "Technology"),
                    ("Travel", "Travel"),
                    ("Vehicles", "Vehicles"),
                    ("Others", "Others"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="hashtags",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="postaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("save", "Save"),
                    ("repost", "Repost"),
                    ("hot", "🔥 Hot"),
                    ("debatable", "🤔 Debatable"),
                    ("agree", "👏 Agree"),
                    ("surprising", "😮 Surprising"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="postaction",
            name="quote_content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="postinsight",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="questionaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="questionfollow",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="readlater",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="reviewaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="reviewfollow",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="bg_color",
            field=models.CharField(
                default="#0ea5e9",
                help_text="Background gradient colour for text stories",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="storyview",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
