# Generated by Django 5.2.13 on 2026-05-04 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0037_perf_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkPreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                ("image_url", models.URLField(blank=True, default="", max_length=500)),
                ("site_name", models.CharField(blank=True, default="", max_length=100)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                ("fetch_failed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-fetched_at"],
            },
        ),
        migrations.CreateModel(
            name="DirectMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=2000)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["sender", "recipient"],
                        name="discussions_sender__dab4e6_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="discussions_recipie_4e05ea_idx",
                    ),
                ],
            },
        ),
    ]
